### ISSUE TITLE
Implement 'combine()' function

### ISSUE THREAD

**Issue by TheBrockEllis** [TheBrockEllis/ZText#11]
This function needs to accept two items from the survivors inventory and check to see if they can be combined into a new super weapon! If a combo weapon is available, we need to remove the two individual items from the survivors inventory and add the new combo weapon.

**Comment by allknowingfrog** [comment]
Having a mix of one and two-word items made this tricky. I ended up adding "and" to the command syntax to differentiate (i.e. "combine pipe and fireworks" rather than "combine pipe fireworks"). Otherwise, combining a one-word item with a two-word item would make command_array ambiguous, and would require a lot of extra searching.

Isn't it bad practice to take in strings and pass them as variable names? Shouldn't we be treating items as objects and storing those objects in rooms, inventory, etc?

Also, apparently there's no undo button for closing an issue. I accidentally closed this one after reading it instead of exiting back to the main issues page. Then reopened it. Then closed it for real.
